LatiMerchant_HandleIntroLatios::
	return



Latios_Text_Intro:
	.string "Oh, a new customer.\p"
	.string "Greetings!\p"
	.string "You've got the face of someone who\n"
	.string "needs more trainer food in their\l"
	.string "diet.\p"
	.string "What a lucky event! I happen to\n"
	.string "have just the right prescription\l"
	.string "for one like yourself.\p"
	.string "All I need in return is a healthy\n"
	.string "heap of crisp cash!$"

Latios_Text_Shop:
	.string "How can I appeal to your selection\n"
	.string "today?$"

Latios_Text_Competition:
	.string "Welcome back, dear customer!\p"
	.string "Please peruse this catalog at your\n"
	.string "own momentum.\p"
	.string "However, I must advise.\p"
	.string "There seems to be a new look-a-like\n"
	.string "the block.\p"
	.string "They say if you buy too many wares\n"
	.string "from them, she may cut you away for\l"
	.string "giving away free pity.\p"
	.string "Beware, dear customer!\p"
	.string "Now then...$"

Latios_Text_Loyalty:
	.string "Ah, the customer!\n"
	.string "You are right on time, always.\p"
	.string "For your continued generosity, I\n"
	.string "will unveil a brand new service to\l"
	.string "line your pockets.\p"
	.string "From this point on, you will receive\n"
	.string "all goods for even less money!\p"
	.string "Please make use of it at your\n"
	.string "convenience.$"

Latios_Text_YourName:
	.string "Customer, I feel it may be rude\n"
	.string "to continue calling you by your\l"
	.string "title in return for showering me in\l"
	.string "so much fortune.\p"
	.string "May I have your name?\p"
	.string "... ... ...\p"
	.string "Ah, {PLAYER}! A splendid moniker.$"

Latios_Text_TodayISaw:
	.string "...Oh. Hello again, {PLAYER}.\p"
	.string "My apologies. I was just a bit\n"
	.string "preoccupied with thoughts.\p"
	.string "$"